export default [
    {
        "id": 1,
        title: 'Venue 1',
        address: 'Address',
        accepting: true,

    },
    {
        "id": 2,
        title: 'Venue 2',
        address: 'Address',
        accepting: true
    },
    {
        "id": 3,
        title: 'Venue 3',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 4,
        title: 'Venue 4',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 5,
        title: 'Venue 5',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 6,
        title: 'Venue 6',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 7,
        title: 'Venue 7',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 8,
        title: 'Venue 8',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 9,
        title: 'Venue 9',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 10,
        title: 'Venue 10',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 11,
        title: 'Venue 11',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 12,
        title: 'Venue 12',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 13,
        title: 'Venue 13',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 14,
        title: 'Venue 14',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 15,
        title: 'Venue 15',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 16,
        title: 'Venue 16',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 17,
        title: 'Venue 17',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 18,
        title: 'Venue 18',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 19,
        title: 'Venue 19',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 20,
        title: 'Venue 20',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 21,
        title: 'Venue 21',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 22,
        title: 'Venue 22',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 23,
        title: 'Venue 23',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 24,
        title: 'Venue 24',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 25,
        title: 'Venue 25',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 26,
        title: 'Venue 26',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 27,
        title: 'Venue 27',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 28,
        title: 'Venue 28',
        address: 'Address',
        accepting: true,
    },
    {
        "id": 29,
        title: 'Venue 29',
        address: 'Address',
        accepting: false,
    },
    {
        "id": 30,
        title: 'Venue 30',
        address: 'Address',
        accepting: true,
    },
]